openapi: 3.2.0
info:
  version: '1.0'
  title: FIWARE-NGSI v2 Specification Attribute Value API
  description: 'TODO: Add a description'
servers:
- url: http://orion.lab.fiware.org/
tags:
- name: Attribute Value
paths:
  /v2/entities/{entityId}/attrs/{attrName}/value:
    get:
      description: 'This operation returns the `value` property with the value of the attribute.

        * If attribute value is JSON Array or Object:

        * If `Accept` header can be expanded to `application/json` or `text/plain` return the value as a JSON with a

        response type of application/json or text/plain (whichever is the first in `Accept` header or

        `application/json` in case of `Accept: */*`).

        * Else return a HTTP error "406 Not Acceptable: accepted MIME types: application/json, text/plain"

        * If attribute value is a string, number, null or boolean:

        * If `Accept` header can be expanded to text/plain return the value as text. In case of a string, citation

        marks are used at the begining and end.

        * Else return a HTTP error "406 Not Acceptable: accepted MIME types: text/plain"

        Response:

        * Successful operation uses 200 OK.

        * Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for

        more details.'
      summary: Get Attribute Value
      tags:
      - Attribute Value
      operationId: Get Attribute Value
      parameters:
      - name: entityId
        in: path
        required: true
        description: Id of the entity in question
        schema:
          type: string
      - name: attrName
        in: path
        required: true
        description: Name of the attribute to be retrieved.
        schema:
          type: string
      - name: type
        in: query
        required: false
        description: 'Entity type, to avoid ambiguity in case there are several

          entities with the same entity id.'
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAttributeValueResponse'
              example:
                address: Ronda de la Comunicacion s/n
                zipCode: 28050
                city: Madrid
                country: Spain
      x-unitTests:
      - request:
          method: GET
          uri: /v2/entities/Bcn_Welt/attrs/address/value
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: RAW
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers:
            Content-Type: application/json
          body: '{  "address": "Ronda de la Comunicacion s/n",  "zipCode": 28050,  "city": "Madrid",  "country": "Spain"}'
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Get Attribute Value1
        x-testDescription: "This operation returns the `value` property with the value of the attribute.\n* If attribute value is JSON Array or Object:\n  * If `Accept` header can be expanded to `application/json` or `text/plain` return the value as a JSON with a\n    response type of application/json or text/plain (whichever is the first in `Accept` header or\n    `application/json` in case of `Accept: */*`).\n  * Else return a HTTP error \"406 Not Acceptable: accepted MIME types: application/json, text/plain\"\n* If attribute value is a string, number, null or boolean:\n  * If `Accept` header can be expanded to text/plain return the value as text. In case of a string, citation\n    marks are used at the begining and end.\n  * Else return a HTTP error \"406 Not Acceptable: accepted MIME types: text/plain\"\nResponse:\n* Successful operation uses 200 OK.\n* Errors use a non-2xx and (optionally) an error payload. See subsection on \"Error Responses\" for\n  more details."
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    put:
      description: 'The request payload is the new attribute value.

        * If the request payload MIME type is `application/json`, then the value of the attribute is set to

        the JSON object or array coded in the payload (if the payload is not a valid JSON document,

        then an error is returned).

        * If the request payload MIME type is `text/plain`, then the following algorithm is applied to the

        payload:

        * If the payload starts and ends with citation-marks (`"`), the value is taken as a string

        (the citation marks themselves are not considered part of the string)

        * If `true` or `false`, the value is taken as a boolean.

        * If `null`, the value is taken as null.

        * If these first three tests ''fail'', the text is interpreted as a number.

        * If not a valid number, then an error is returned and the attribute''s value is unchanged.

        The payload MIME type in the request is specified in the `Content-Type` HTTP header.

        Response:

        * Successful operation uses 204 No Content

        * Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for

        more details.'
      summary: Update Attribute Value
      tags:
      - Attribute Value
      operationId: Update Attribute Value
      parameters:
      - name: entityId
        in: path
        required: true
        description: Id of the entity to be updated.
        schema:
          type: string
      - name: attrName
        in: path
        required: true
        description: Attribute name.
        schema:
          type: string
      - name: Content-Type
        in: header
        required: true
        description: ''
        schema:
          type: string
      - name: type
        in: query
        required: false
        description: 'Entity type, to avoid ambiguity in case there are several

          entities with the same entity id.'
        schema:
          type: string
      responses:
        '200':
          description: ''
      x-unitTests:
      - request:
          method: PUT
          uri: /v2/entities/Bcn_Welt/attrs/address/value
          headers:
            Content-Type: application/json
          body: '{  "address": "Ronda de la Comunicacion s/n",  "zipCode": 28050,  "city": "Madrid",  "country": "Spain"}'
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Update Attribute Value1
        x-testDescription: "The request payload is the new attribute value.\n* If the request payload MIME type is `application/json`, then the value of the attribute is set to\n  the JSON object or array coded in the payload (if the payload is not a valid JSON document,\n  then an error is returned).\n* If the request payload MIME type is `text/plain`, then the following algorithm is applied to the\n  payload:\n  * If the payload starts and ends with citation-marks (`\"`), the value is taken as a string\n    (the citation marks themselves are not considered part of the string)\n  * If `true` or `false`, the value is taken as a boolean.\n  * If `null`, the value is taken as null.\n  * If these first three tests 'fail', the text is interpreted as a number.\n  * If not a valid number, then an error is returned and the attribute's value is unchanged.\nThe payload MIME type in the request is specified in the `Content-Type` HTTP header.\nResponse:\n* Successful operation uses 204 No Content\n* Errors use a non-2xx and (optionally) an error payload. See subsection on \"Error Responses\" for\n  more details."
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAttributeValueRequest'
        required: true
components:
  schemas:
    UpdateAttributeValueRequest:
      title: Update Attribute Value request
      example:
        address: Ronda de la Comunicacion s/n
        zipCode: 28050
        city: Madrid
        country: Spain
      type: object
      properties:
        address:
          description: ''
          example: Ronda de la Comunicacion s/n
          type: string
        zipCode:
          description: ''
          example: 28050
          type: integer
          format: int32
        city:
          description: ''
          example: Madrid
          type: string
        country:
          description: ''
          example: Spain
          type: string
      required:
      - address
      - zipCode
      - city
      - country
    GetAttributeValueResponse:
      title: Get Attribute Value response
      example:
        address: Ronda de la Comunicacion s/n
        zipCode: 28050
        city: Madrid
        country: Spain
      type: object
      properties:
        address:
          description: ''
          example: Ronda de la Comunicacion s/n
          type: string
        zipCode:
          description: ''
          example: 28050
          type: integer
          format: int32
        city:
          description: ''
          example: Madrid
          type: string
        country:
          description: ''
          example: Spain
          type: string
      required:
      - address
      - zipCode
      - city
      - country
